backend:
  name: github
  repo: virenrshah/bbwebsite

media_folder: media_folder

collections:
- name: src/pages/team
  label: Team
  folder: team
  create: true
  fields:
    - {name: title, label: Title}
    - {name: body, label: Body, widget: markdown}
